use colored::Colorize;
use std::fs;
use std::path::Path;

/// Generate a new migration file.
pub fn new_migration(name: &str) -> Result<(), String> {
    validate_name(name)?;

    let migrations_dir = Path::new("src/migrations");

    if !migrations_dir.exists() {
        fs::create_dir_all(migrations_dir)
            .map_err(|e| format!("Failed to create migrations directory: {}", e))?;
        println!("  {} Created {}", "✓".green(), "src/migrations/".cyan());
    }

    let timestamp = chrono::Utc::now().format("%Y%m%d_%H%M%S").to_string();
    let module_name = format!("m{}_{}", timestamp, name);
    let filename = format!("{}.rs", module_name);
    let filepath = migrations_dir.join(&filename);

    if filepath.exists() {
        return Err(format!("Migration file already exists: {}", filename));
    }

    let template = generate_template(name);
    fs::write(&filepath, template).map_err(|e| format!("Failed to write migration file: {}", e))?;
    println!(
        "  {} Created {}",
        "✓".green(),
        format!("src/migrations/{}", filename).cyan()
    );

    update_mod_rs(migrations_dir, &module_name)?;

    println!();
    println!(
        "  Migration created. Add your schema changes to the {} and {} methods.",
        "up".cyan(),
        "down".cyan()
    );
    println!();

    Ok(())
}

fn validate_name(name: &str) -> Result<(), String> {
    if name.is_empty() {
        return Err("Migration name cannot be empty".to_string());
    }

    for c in name.chars() {
        if !c.is_ascii_lowercase() && !c.is_ascii_digit() && c != '_' {
            return Err(format!(
                "Migration name must be lowercase alphanumeric with underscores, got '{}'",
                c
            ));
        }
    }

    if name.starts_with('_') || name.ends_with('_') {
        return Err("Migration name cannot start or end with underscore".to_string());
    }

    Ok(())
}

fn generate_template(name: &str) -> String {
    let readable_name = name.replace('_', " ");

    format!(
        r#"//! Migration: {readable_name}

use rapina::sea_orm_migration;
use rapina::migration::prelude::*;

#[derive(DeriveMigrationName)]
pub struct Migration;

#[async_trait]
impl MigrationTrait for Migration {{
    async fn up(&self, manager: &SchemaManager) -> Result<(), DbErr> {{
        todo!("Write your migration here")
    }}

    async fn down(&self, manager: &SchemaManager) -> Result<(), DbErr> {{
        todo!("Write your rollback here")
    }}
}}
"#
    )
}

pub(crate) fn update_mod_rs(migrations_dir: &Path, module_name: &str) -> Result<(), String> {
    let mod_path = migrations_dir.join("mod.rs");

    if mod_path.exists() {
        let content =
            fs::read_to_string(&mod_path).map_err(|e| format!("Failed to read mod.rs: {}", e))?;

        if content.contains("rapina::migrations!") {
            let new_mod = format!("mod {};\n\n", module_name);
            let updated = format!("{}{}", new_mod, content);
            let updated = add_to_migrations_macro(&updated, module_name);
            fs::write(&mod_path, updated).map_err(|e| format!("Failed to update mod.rs: {}", e))?;
        } else {
            let updated = format!("{}mod {};\n", content, module_name);
            fs::write(&mod_path, updated).map_err(|e| format!("Failed to update mod.rs: {}", e))?;
        }
    } else {
        let content = format!(
            r#"mod {module_name};

rapina::migrations! {{
    {module_name},
}}
"#
        );
        fs::write(&mod_path, &content).map_err(|e| format!("Failed to create mod.rs: {}", e))?;
    }

    println!(
        "  {} Updated {}",
        "✓".green(),
        "src/migrations/mod.rs".cyan()
    );

    Ok(())
}

pub(crate) fn add_to_migrations_macro(content: &str, module_name: &str) -> String {
    if let Some(macro_start) = content.find("rapina::migrations! {") {
        let after_macro = &content[macro_start..];
        if let Some(close_brace) = after_macro.rfind('}') {
            let insertion_point = macro_start + close_brace;
            let mut result = String::new();
            result.push_str(&content[..insertion_point]);
            result.push_str(&format!("    {},\n", module_name));
            result.push_str(&content[insertion_point..]);
            return result;
        }
    }
    content.to_string()
}

/// Content for `src/bin/rapina_migrate.rs`.
pub(crate) fn generate_migrate_bin_rs() -> String {
    r#"//! Migration runner — generated by `rapina migrate init`.
//! Apply, roll back, or inspect migrations without touching the web server.
//!
//! Run via the Rapina CLI:
//!   rapina migrate up
//!   rapina migrate down [--steps N]
//!   rapina migrate status
//!   rapina migrate fresh
//!   rapina migrate reset
//!
//! NOTE: The `#[path]` attribute below assumes the default Rapina project layout:
//!   src/bin/rapina_migrate.rs  ← this file
//!   src/migrations/mod.rs      ← your migrations module
//!
//! If you have customised your directory structure, update the path below
//! to point at your actual migrations/mod.rs file.

#[path = "../migrations/mod.rs"]
mod migrations;

#[tokio::main]
async fn main() {
    rapina::migration::run_cli::<migrations::Migrator>().await;
}
"#
    .to_string()
}

/// Walk up from `start` until a directory containing `Cargo.toml` is found.
/// Returns `Err` if no such directory exists up to the filesystem root.
pub(crate) fn find_project_root(start: &std::path::Path) -> Result<std::path::PathBuf, String> {
    let mut dir = start
        .canonicalize()
        .map_err(|e| format!("Failed to resolve current directory: {e}"))?;
    loop {
        if dir.join("Cargo.toml").exists() {
            return Ok(dir);
        }
        match dir.parent() {
            Some(parent) => dir = parent.to_path_buf(),
            None => {
                return Err(
                    "Could not find project root (no Cargo.toml found in current directory or any \
                     parent). Run this command from inside your Rapina project."
                        .to_string(),
                );
            }
        }
    }
}

/// Returns `Ok(())` if `src/bin/rapina_migrate.rs` exists relative to `project_root`,
/// or an error with instructions to run `rapina migrate init`.
pub(crate) fn check_migrate_bin(project_root: &std::path::Path) -> Result<(), String> {
    let bin_path = project_root
        .join("src")
        .join("bin")
        .join("rapina_migrate.rs");
    if bin_path.exists() {
        Ok(())
    } else {
        Err("migrate binary not found (src/bin/rapina_migrate.rs).\n\
             Run 'rapina migrate init' to set it up for this project."
            .to_string())
    }
}

/// Create `src/bin/rapina_migrate.rs` in `project_root`.
/// Returns an error if the file already exists.
pub fn init_migrate_bin(project_root: &std::path::Path) -> Result<(), String> {
    let bin_dir = project_root.join("src").join("bin");
    fs::create_dir_all(&bin_dir).map_err(|e| format!("Failed to create src/bin/: {e}"))?;

    let bin_path = bin_dir.join("rapina_migrate.rs");
    if bin_path.exists() {
        return Err(
            "src/bin/rapina_migrate.rs already exists. Remove it first if you want to regenerate."
                .to_string(),
        );
    }

    fs::write(&bin_path, generate_migrate_bin_rs())
        .map_err(|e| format!("Failed to write rapina_migrate.rs: {e}"))?;
    println!(
        "  {} Created {}",
        "✓".green(),
        "src/bin/rapina_migrate.rs".cyan()
    );
    println!();
    println!("  Run migrations with:");
    println!("    rapina migrate up");
    println!("    rapina migrate down [--steps N]");
    println!("    rapina migrate status");
    println!("    rapina migrate fresh");
    println!("    rapina migrate reset");
    println!();
    Ok(())
}

/// Shell out to `cargo run -q --bin rapina_migrate -- <args>`.
///
/// Detects the project root by walking up from the current directory looking for
/// `Cargo.toml`. This means the command works correctly even when invoked from a
/// subdirectory (e.g. `src/`).
///
/// Inherits the current process environment (including DATABASE_URL loaded from .env).
/// Streams stdout/stderr directly to the terminal.
pub fn run_migrate_cmd(subcommand_args: &[&str]) -> Result<(), String> {
    let cwd =
        std::env::current_dir().map_err(|e| format!("Failed to get current directory: {e}"))?;
    run_migrate_cmd_from(subcommand_args, &cwd)
}

/// Like [`run_migrate_cmd`] but accepts an explicit starting directory.
/// Separated to allow unit testing without mutating the global CWD.
pub(crate) fn run_migrate_cmd_from(
    subcommand_args: &[&str],
    cwd: &std::path::Path,
) -> Result<(), String> {
    let project_root = find_project_root(cwd)?;
    check_migrate_bin(&project_root)?;

    println!("  {} Compiling migrate binary...", "…".cyan());

    let status = std::process::Command::new("cargo")
        .args(["run", "-q", "--bin", "rapina_migrate", "--"])
        .args(subcommand_args)
        .current_dir(&project_root)
        .status()
        .map_err(|e| format!("Failed to run cargo: {e}"))?;

    if status.success() {
        Ok(())
    } else {
        Err(format!(
            "rapina_migrate exited with status {}",
            status.code().unwrap_or(-1)
        ))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_validate_name_valid() {
        assert!(validate_name("create_users").is_ok());
        assert!(validate_name("add_email_to_users").is_ok());
        assert!(validate_name("create_posts_table").is_ok());
    }

    #[test]
    fn test_validate_name_invalid() {
        assert!(validate_name("").is_err());
        assert!(validate_name("CreateUsers").is_err());
        assert!(validate_name("create-users").is_err());
        assert!(validate_name("_create_users").is_err());
        assert!(validate_name("create_users_").is_err());
    }

    #[test]
    fn test_generate_template() {
        let template = generate_template("create_users");
        assert!(template.contains("MigrationTrait for Migration"));
        assert!(template.contains("async fn up"));
        assert!(template.contains("async fn down"));
        assert!(template.contains("use rapina::migration::prelude::*"));
    }

    #[test]
    fn test_generate_migrate_bin_content() {
        let content = generate_migrate_bin_rs();
        assert!(content.contains("#[path = \"../migrations/mod.rs\"]"));
        assert!(content.contains("mod migrations"));
        assert!(content.contains("rapina::migration::run_cli::<migrations::Migrator>()"));
        assert!(content.contains("#[tokio::main]"));
    }

    #[test]
    fn test_check_migrate_bin_missing() {
        let dir = tempfile::tempdir().unwrap();
        let err = check_migrate_bin(dir.path()).unwrap_err();
        assert!(err.contains("rapina migrate init"));
    }

    #[test]
    fn test_check_migrate_bin_present() {
        let dir = tempfile::tempdir().unwrap();
        let bin_dir = dir.path().join("src").join("bin");
        std::fs::create_dir_all(&bin_dir).unwrap();
        std::fs::write(bin_dir.join("rapina_migrate.rs"), "fn main() {}").unwrap();
        assert!(check_migrate_bin(dir.path()).is_ok());
    }

    #[test]
    fn test_find_project_root_from_project_dir() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("Cargo.toml"), "[package]").unwrap();
        let root = find_project_root(dir.path()).unwrap();
        assert_eq!(root, dir.path().canonicalize().unwrap());
    }

    #[test]
    fn test_find_project_root_from_subdirectory() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("Cargo.toml"), "[package]").unwrap();
        let subdir = dir.path().join("src").join("handlers");
        std::fs::create_dir_all(&subdir).unwrap();
        let root = find_project_root(&subdir).unwrap();
        assert_eq!(root, dir.path().canonicalize().unwrap());
    }

    #[test]
    fn test_find_project_root_not_found() {
        // Use a temp dir with no Cargo.toml anywhere up the tree.
        // We can't guarantee that, so we test the error message when
        // the immediate dir has no Cargo.toml and has no parent with one
        // by creating a completely isolated temp path with no Cargo.toml.
        let dir = tempfile::tempdir().unwrap();
        // No Cargo.toml written — should error unless one of the parents has it.
        // In CI this won't have Cargo.toml above /tmp. In dev it might. So we
        // test the found-binary-missing path instead: root found but no bin.
        let result = find_project_root(dir.path());
        // Either Ok (found a Cargo.toml up the tree) or Err (didn't find one).
        // Either way the function shouldn't panic.
        let _ = result;
    }

    #[test]
    fn test_run_migrate_cmd_fails_without_migrate_bin() {
        // run_migrate_cmd_from should fail with a clear error when rapina_migrate.rs
        // is missing, even when called from a valid project root.
        // Uses run_migrate_cmd_from to avoid mutating the global CWD.
        let dir = tempfile::tempdir().unwrap();
        std::fs::write(dir.path().join("Cargo.toml"), "[package]").unwrap();
        let err = run_migrate_cmd_from(&["up"], dir.path()).unwrap_err();
        assert!(err.contains("rapina migrate init"));
    }

    #[test]
    fn test_init_migrate_bin_creates_file() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::create_dir_all(dir.path().join("src").join("migrations")).unwrap();
        init_migrate_bin(dir.path()).unwrap();
        let bin_path = dir.path().join("src").join("bin").join("rapina_migrate.rs");
        assert!(bin_path.exists());
        let content = std::fs::read_to_string(bin_path).unwrap();
        assert!(content.contains("run_cli"));
    }

    #[test]
    fn test_init_migrate_bin_already_exists() {
        let dir = tempfile::tempdir().unwrap();
        std::fs::create_dir_all(dir.path().join("src").join("bin")).unwrap();
        let bin_path = dir.path().join("src").join("bin").join("rapina_migrate.rs");
        std::fs::write(&bin_path, "existing").unwrap();
        let err = init_migrate_bin(dir.path()).unwrap_err();
        assert!(err.contains("already exists"));
    }
}
